# Generated by Django 2.1.7 on 2019-08-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'permissions': (('patreon', 'Patreon gallery access'),)},
        ),
    ]
